language: generic 

services:
  - docker

before_install:
  - docker build -t achamchi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run achamchi/react-test npm test -- --coverage

after_success:
  - docker build -t achamchi/multi-client ./client
  - docker build -t achamchi/multi-nginx ./nginx
  - docker build -t achamchi/multi-server ./server
  - docker build -t achamchi/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
  
  - docker push -t achamchi/multi-client
  - docker push -t achamchi/multi-nginx
  - docker push -t achamchi/multi-server
  - docker push -t achamchi/multi-worker
